// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PubGaming.Database;

#nullable disable

namespace PubGaming.Database.Migrations
{
    [DbContext(typeof(PgDbContext))]
    partial class PgDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PubGaming.Database.Entites.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GameType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("PubGaming.Database.Entites.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer");

                    b.Property<int?>("SetId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SetId");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("PubGaming.Database.Entites.QuestionTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionType")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("QuestionTemplates", (string)null);
                });

            modelBuilder.Entity("PubGaming.Database.Entites.Set", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("GameId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("Sets", (string)null);
                });

            modelBuilder.Entity("PubGaming.Database.Entites.SetTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SetTemplates", (string)null);
                });

            modelBuilder.Entity("PubGaming.Database.Entites.SetTemplateQuestionTemplate", b =>
                {
                    b.Property<int>("QuestionTemplateId")
                        .HasColumnType("integer");

                    b.Property<int>("SetTemplateId")
                        .HasColumnType("integer");

                    b.HasKey("QuestionTemplateId", "SetTemplateId");

                    b.HasIndex("SetTemplateId");

                    b.ToTable("SetTemplatesQuestionTemplates", (string)null);
                });

            modelBuilder.Entity("PubGaming.Database.Entites.Question", b =>
                {
                    b.HasOne("PubGaming.Database.Entites.Set", "Set")
                        .WithMany("Questions")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsMany("PubGaming.Database.Entites.Question.Answers#PubGaming.Database.Entites.Answer", "Answers", b1 =>
                        {
                            b1.Property<int>("QuestionId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("AnswerNo")
                                .HasColumnType("integer");

                            b1.Property<bool>("IsCorrect")
                                .HasColumnType("boolean");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("QuestionId", "Id");

                            b1.ToTable("Questions", (string)null);

                            b1.ToJson("Answers");

                            b1.WithOwner()
                                .HasForeignKey("QuestionId");
                        });

                    b.Navigation("Answers");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("PubGaming.Database.Entites.QuestionTemplate", b =>
                {
                    b.OwnsMany("PubGaming.Database.Entites.QuestionTemplate.Answers#PubGaming.Database.Entites.Answer", "Answers", b1 =>
                        {
                            b1.Property<int>("QuestionTemplateId")
                                .HasColumnType("integer");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            b1.Property<int>("AnswerNo")
                                .HasColumnType("integer");

                            b1.Property<bool>("IsCorrect")
                                .HasColumnType("boolean");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("QuestionTemplateId", "Id");

                            b1.ToTable("QuestionTemplates", (string)null);

                            b1.ToJson("Answers");

                            b1.WithOwner()
                                .HasForeignKey("QuestionTemplateId");
                        });

                    b.Navigation("Answers");
                });

            modelBuilder.Entity("PubGaming.Database.Entites.Set", b =>
                {
                    b.HasOne("PubGaming.Database.Entites.Game", "Game")
                        .WithMany("Sets")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Game");
                });

            modelBuilder.Entity("PubGaming.Database.Entites.SetTemplateQuestionTemplate", b =>
                {
                    b.HasOne("PubGaming.Database.Entites.QuestionTemplate", "QuestionTemplate")
                        .WithMany("SetTemplateQuestionTemplates")
                        .HasForeignKey("QuestionTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PubGaming.Database.Entites.SetTemplate", "SetTemplate")
                        .WithMany("SetTemplatesQuestionTemplates")
                        .HasForeignKey("SetTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QuestionTemplate");

                    b.Navigation("SetTemplate");
                });

            modelBuilder.Entity("PubGaming.Database.Entites.Game", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("PubGaming.Database.Entites.QuestionTemplate", b =>
                {
                    b.Navigation("SetTemplateQuestionTemplates");
                });

            modelBuilder.Entity("PubGaming.Database.Entites.Set", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("PubGaming.Database.Entites.SetTemplate", b =>
                {
                    b.Navigation("SetTemplatesQuestionTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
